spring:
  messages:
    basename: messages
  devtools:
    livereload:
      enabled: false
  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML
    suffix: .html
    servlet:
      content-type: text/html
  datasource:
    url: jdbc:sqlserver://183.111.104.67:20170;DatabaseName=dtnsm_demo
    username: sa
    password: safe123!@#
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  flyway:
    locations: classpath:/db/migration/prod
    baseline-on-migrate: true
    encoding: UTF-8
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
        use_sql_comments: true

mybatis:
  type-aliases-package: com.dtnsm.lms.mybatis.dto

file:
  default-base: C://UploadFiles//ssdemo//lms//
  cv-upload-dir: C://UploadFiles//ssdemo//lms//CV//
  border-upload-dir: C://UploadFiles//ssdemo//lms//upload//border//
  border-photo-upload-dir: C://UploadFiles//ssdemo//lms//upload//border//PhotoUpload//
  course-upload-dir: C://UploadFiles//ssdemo//lms//upload//course//
  course-section-upload-dir: C://UploadFiles//ssdemo//lms//upload//course//section//
  course-photo-upload-dir: C://UploadFiles//ssdemo//lms//upload//course//PhotoUpload//
  schedule-upload-dir: C://UploadFiles//ssdemo//lms//upload//schedule//
  course-quiz-upload-dir: C://UploadFiles//ssdemo//lms//upload//course//quiz//
  document-upload-dir: C://UploadFiles//ssdemo//lms//upload//document//
  survey-upload-dir: C://UploadFiles//ssdemo//lms//upload//survey//
  binder-jd-upload-dir: C://UploadFiles//ssdemo//lms//upload//binder//jd//
  xdoc-upload-dir: C://UploadFiles//ssdemo//lms//upload//xdoc//
  certificate-upload-dir: C://UploadFiles//ssdemo//lms//upload//certificate//
  training-log-upload-dir: C://UploadFiles//ssdemo//trainingLog
  binder-dir: C://UploadFiles//ssdemo//binder//


image-file:
  matric: C://UploadFiles//ssdemo//lms//images//matrix//
  course: C://UploadFiles//ssdemo//lms//images//course//
  pdf: C://UploadFiles//ssdemo//lms//images//pdf//


groupdocs:
  license: C://Servers//deploy//GroupDocs.Total.Java.lic



