server:
  port: 8080
  domain: lms.safesoft.co.kr
  link: "http://lms.safesoft.co.kr"

spring:
  jpa:
    open-in-view: true
    properties:
      org:
        hibernate:
          envers:
            audit_table_suffix: _audit
            modified_flag_suffix: _changed
            store_data_at_delete: true
  profiles:
    active: prod
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
  mail:
    host: gw.dtnsm.com
    port: 25
    protocol: smtp
    username: sanomedics@dtnsm.com
    password: qwer1234!
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

logging:
  level:
    root: INFO
    org.springframework:
      web: INFO
      security: INFO
      session: INFO
      data: INFO
      jdbc:
        core:
          JdbcTemplate: INFO
          StatementCreatorUtils: TRACE
    com.dtnsm: DEBUG
    org.apache.tiles: DEBUG

#Site별 설정.
site:
  code: "SafeSoft"
  link: "http://www.safesoft.co.kr/"
  #  iso-title: "ISO 14155"
  company-title: "SafeSoft"
  company-kor-title: "세이프소프트"
  footer-msg: "Copyright© SafeSoft Co.,Ltd. All Rights Reserved."
  footer-img: "/default/login/images/logo_safesoft.jpg"
  image-logo: "/default/login/images/logo_safesoft.jpg"
  login-image: "/default/login/images/signup-image.jpg"

  #세션 타이머(초 단위)
  session-timer: "1800"
  session-minute: "30"
  session-second: "00"

meta:
  description: "SafeSoft e-LMS Management System"
  keywords: "세이프소프트,e-LMS"

employee:
  number-count: 9

mail:
  notice:
    name: SanoMedics(e-SOP)
    address: no-reply@dtnsm.com

#UserMenu 관련 sano
my:
  status: "교육현황"
  log-update: "Training Log Upload"
  log: "Employee Training Log"
  cv: "Curriculum Vitae"
  jd: "Job Description"
  cert-upload: "수료증 Upload"
  user-info: "사용자정보"
binder:
  cv: "Curriculum Vitae"
  jd: "job Description"
  log-sop: "Employee Training Log(SOP)"
  log-tm: "Employee Training Log(TM)"
  cert: "Certification"

gw:
  code: 4 #법인코드(1:디티앤씨, 2:디티앤씨알오, 4:디티앤사노메딕스)
