spring:
  messages:
    basename: messages
  devtools:
    livereload:
      enabled: false
  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML
    #    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  datasource:
    url: jdbc:sqlserver://localhost:20170;DatabaseName=test_lms
    username: sa
    password: safe123!@#
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  flyway:
    #      url: jdbc:sqlserver://localhost:1433;DatabaseName=elearning
    #      user: sa
    #      password: Dtncro@123##
    locations: classpath:/db/migration/lms
    baseline-on-migrate: false
    encoding: UTF-8
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: pub147@gmail.com
#    password: cksdb0826
    password: hllzmxukahrxghrm
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

mybatis:
  type-aliases-package: com.dtnsm.lms.mybatis.dto

#logging:
#  level:
#    root: ERROR
#    org.springframework.web: ERROR
#    com.dtnsm.lms: DEBUG
#    org.hibernate: ERROR


file:
  default-base: C://UploadFiles//lms//
  border-upload-dir: C://UploadFiles//lms//upload//border//
  border-photo-upload-dir: C://UploadFiles//lms//upload//border//PhotoUpload//
  course-upload-dir: C://UploadFiles//lms//upload//course//
  course-section-upload-dir: C://UploadFiles//lms//upload//course//section//
  course-photo-upload-dir: C://UploadFiles//lms//upload//course//PhotoUpload//
  schedule-upload-dir: C://UploadFiles//lms//upload//schedule//
  course-quiz-upload-dir: C://UploadFiles//lms//upload//course//quiz//
  document-upload-dir: C://UploadFiles//lms//upload//document//
  survey-upload-dir: C://UploadFiles//lms//upload//survey//
  binder-jd-upload-dir: C://UploadFiles//lms//upload//binder//jd//
  xdoc-upload-dir: C://UploadFiles//lms//upload//xdoc//



image-file:
  matric: C://UploadFiles//lms//images//matrix//
  course: C://UploadFiles//lms//images//course//
  pdf: C://UploadFiles//lms//images//pdf//


